#!/bin/bash
# ============================================================
#  Synapse VPS Deploy Script
#  Запускать на ЧИСТОМ Ubuntu 22.04+ VPS
#  Использование: chmod +x deploy.sh && sudo ./deploy.sh
# ============================================================

set -e

# ==================== НАСТРОЙКИ ====================
# Замени на свои значения перед запуском!

DOMAIN="synapse.example.com"        # Твой домен
EMAIL="admin@synapse.app"           # Email для Let's Encrypt
DB_PASSWORD="$(openssl rand -hex 16)"
REDIS_PASSWORD="$(openssl rand -hex 16)"
NEXTAUTH_SECRET="$(openssl rand -base64 32)"
CRON_SECRET="$(openssl rand -hex 16)"
ADMIN_PASSWORD="$(openssl rand -base64 16)"

# ==================== 1. СИСТЕМНЫЕ ПАКЕТЫ ====================
echo ">>> [1/7] Обновление системы и установка Docker..."
apt-get update && apt-get upgrade -y
apt-get install -y curl git ufw nginx certbot python3-certbot-nginx

# Docker
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
fi

# Docker Compose plugin
if ! docker compose version &> /dev/null; then
    apt-get install -y docker-compose-plugin
fi

# ==================== 2. ФАЙРВОЛ ====================
echo ">>> [2/7] Настройка файрвола..."
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# ==================== 3. ПРОЕКТ ====================
echo ">>> [3/7] Подготовка проекта..."
mkdir -p /opt/synapse
cd /opt/synapse

# Если проект загружен вручную (scp/rsync), пропустить git clone
if [ ! -f "package.json" ]; then
    echo "!!! Скопируй проект в /opt/synapse/ перед запуском этого скрипта"
    echo "    Пример: scp -r ./synapse-app/* user@server:/opt/synapse/"
    exit 1
fi

# ==================== 4. ENV ФАЙЛ ====================
echo ">>> [4/7] Создание .env.production..."
cat > .env.production << EOF
# === GENERATED BY DEPLOY SCRIPT ===
# Database (внутри Docker-сети)
DATABASE_URL="postgresql://synapse:${DB_PASSWORD}@postgres:5432/synapse?schema=public"

# NextAuth
NEXTAUTH_URL="https://${DOMAIN}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"

# Redis (внутри Docker-сети)
REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379"

# Admin
ADMIN_EMAIL="${EMAIL}"
ADMIN_PASSWORD="${ADMIN_PASSWORD}"

# Payments
USDT_WALLET_ADDRESS="TGj7KqGVtqJrPSPzBrtMpX41QaNdqTBk4U"
CRON_SECRET="${CRON_SECRET}"
TRONGRID_API_URL="https://api.trongrid.io"
TRONGRID_API_KEY="baf1c43e-e95a-4ae9-a85d-91e894892fdf"

# URLs
NEXT_PUBLIC_SOCKET_URL="https://${DOMAIN}"
NEXT_PUBLIC_APP_URL="https://${DOMAIN}"
SOCKET_PORT=3001

# WebRTC
STUN_SERVER_URL="stun:stun.l.google.com:19302"
TURN_SERVER_URL=""
TURN_USERNAME=""
TURN_PASSWORD=""
EOF

# Для docker-compose
cat > .env << EOF
DB_PASSWORD=${DB_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
EOF

echo ">>> ADMIN_PASSWORD: ${ADMIN_PASSWORD}"
echo ">>> Запиши этот пароль! Он больше не будет показан."

# ==================== 5. СБОРКА И ЗАПУСК ====================
echo ">>> [5/7] Сборка Docker-контейнеров..."
docker compose build --no-cache

echo ">>> Запуск контейнеров..."
docker compose up -d

# Ждём PostgreSQL
echo ">>> Ожидание готовности PostgreSQL..."
sleep 5

# Prisma: применяем schema к БД
echo ">>> Применение Prisma schema..."
docker compose exec app npx prisma db push --accept-data-loss

# ==================== 6. NGINX + SSL ====================
echo ">>> [6/7] Настройка Nginx + SSL..."

# Копируем конфиг
cp deploy/nginx.conf /etc/nginx/sites-available/synapse
sed -i "s/synapse.example.com/${DOMAIN}/g" /etc/nginx/sites-available/synapse
ln -sf /etc/nginx/sites-available/synapse /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Сначала без SSL (для certbot)
cat > /etc/nginx/sites-available/synapse-temp << TEMPEOF
server {
    listen 80;
    server_name ${DOMAIN};
    location / { proxy_pass http://127.0.0.1:3000; }
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
}
TEMPEOF
ln -sf /etc/nginx/sites-available/synapse-temp /etc/nginx/sites-enabled/synapse
nginx -t && systemctl reload nginx

# Получаем SSL-сертификат
mkdir -p /var/www/certbot
certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos -m "${EMAIL}"

# Теперь ставим полный конфиг с SSL
cp deploy/nginx.conf /etc/nginx/sites-available/synapse
sed -i "s/synapse.example.com/${DOMAIN}/g" /etc/nginx/sites-available/synapse
ln -sf /etc/nginx/sites-available/synapse /etc/nginx/sites-enabled/synapse
rm -f /etc/nginx/sites-available/synapse-temp
nginx -t && systemctl reload nginx

# Автообновление сертификата
systemctl enable certbot.timer

# ==================== 7. CRON ДЛЯ ПЛАТЕЖЕЙ ====================
echo ">>> [7/7] Настройка cron для проверки платежей..."
(crontab -l 2>/dev/null; echo "*/2 * * * * curl -s -X POST -H 'Authorization: Bearer ${CRON_SECRET}' https://${DOMAIN}/api/payments/check > /dev/null") | crontab -

# ==================== ГОТОВО ====================
echo ""
echo "============================================"
echo "  Synapse успешно развёрнут!"
echo "============================================"
echo ""
echo "  Сайт:     https://${DOMAIN}"
echo "  Админка:  https://${DOMAIN}/admin/login"
echo "  Email:    ${EMAIL}"
echo "  Пароль:   ${ADMIN_PASSWORD}"
echo ""
echo "  Полезные команды:"
echo "    docker compose logs -f          # логи"
echo "    docker compose restart          # перезапуск"
echo "    docker compose down             # остановка"
echo "    docker compose up -d --build    # пересборка"
echo ""
echo "  Проверка платежей: каждые 2 мин (cron)"
echo "============================================"
